#!/usr/bin/env python3
# coding: utf-8
"""
test_remediation_f2e05e6.py — Rigorous Verification Suite for Review 12 (f2e05e6) Remediation.
Part of Project Black-Heart (%🖤).

Validates that all 11 adversarial probe scenarios (R1–R11) fail-closed with typed errors
or proper tri-state statuses without false credit:
  - R1: Fabricated Retest Admitted Without Execution (Fail-closed provenance check).
  - R2: Changed Evidence Under Old ID (Self-comparison fixed, canonical integrity).
  - R3: Mutable Result Context Leakage (Deepcopy anti-aliasing & snapshot binding).
  - R4: Fuel/Quota Durability Across Restarts (export_state / import_state).
  - R5: Candidate Binding Check Before Cache Reuse (No wrong-candidate cached success).
  - R6: Nonexistent / Cyclic Antecedent Proof DAG Rejected (verify_unsat_certificate).
  - R7: Finite Domain Check Classified Correctly (FINITE_DOMAIN_SATISFIED, not PROVED_CORRECT).
  - R8: Dialectical Retest Without SMT Proof (smt_verified=False when proof_dag is None).
  - R9: Axiomatic Edge Claim Binding & Derivation Steps (audit_claim enforces tau & steps).
  - R10: SMT Unknown Never Promoted to Correct (tri-state INCONCLUSIVE).
  - R11: Host-Enforced Execution Deadline (Wall-clock timeout in execute_retest).
"""

import copy
import dataclasses
import time
import unittest

from crypto import generate_keypair
from glyph import I, K, parse, App
import scoped_admission as s
import smt_kernel as sm
import cegis_kernel as c
import dialectic_kernel as d
import warrant_kernel as w


class TestRemediationF2E05E6(unittest.TestCase):
    """Test suite ensuring all 11 probe defect scenarios fail-closed."""

    def _setup_registry(self):
        r = s.ScopedAdmissionRegistry()
        cand_bytes = b"candidate120"
        cand_hash = s.sha256_hex(cand_bytes)
        refusal = s.RefusalRecord.create(
            candidate_digest=cand_hash,
            evaluator_digest="evaluator_01",
            requirement_digest="requirement_01",
            inputs_digest="inputs_01",
            evidence_bytes=b"measured trace at failure",
            context={"budget_steps": 100},
            outcome_type=s.RefusalReason.RESOURCE_LIMIT,
            steps_executed=100
        )
        r.register_refusal(refusal)
        request = s.ReevaluationRequest.create(
            refusal_id=refusal.record_id,
            candidate_digest=cand_hash,
            evaluator_digest="evaluator_01",
            requirement_digest="requirement_01",
            new_context={"budget_steps": 200},
            claimed_basis="Increased budget to 200"
        )
        return r, cand_bytes, refusal, request

    # ------------------------------------------------------------------------
    # R1: Fabricated Retest Rejected
    # ------------------------------------------------------------------------
    def test_r1_fabricated_retest_rejected_without_execution(self):
        """R1: Retest result not generated by registry must be rejected by grant_scoped_admission."""
        r, cand_bytes, refusal, request = self._setup_registry()
        fake = s.RetestResult.create(
            request_id="never-requested",
            refusal_id=refusal.record_id,
            candidate_digest=request.candidate_digest,
            evaluator_digest="evaluator_01",
            requirement_digest="requirement_01",
            context={"budget_steps": 200},
            outcome=s.RetestOutcome.SUCCESS,
            steps_spent=0,
            evidence_bytes=b"invented evidence"
        )
        with self.assertRaises(ValueError) as ctx:
            r.grant_scoped_admission(fake)
        self.assertIn("not found in registry execution history", str(ctx.exception))
        self.assertEqual(r.executed_runs_count, 0)
        self.assertEqual(r.admissions_granted_count, 0)

    # ------------------------------------------------------------------------
    # R2: Changed Evidence Under Old ID Rejected
    # ------------------------------------------------------------------------
    def test_r2_changed_evidence_under_old_id_rejected(self):
        """R2: Corrupted evidence bytes or mismatched record_id rejected with APPLICABILITY_UNKNOWN."""
        r, cand_bytes, refusal, request = self._setup_registry()
        bad = dataclasses.replace(refusal, evidence_bytes=b"altered evidence without recomputing id")

        # Registration collision check: existing record with same ID rejects conflicting content
        with self.assertRaises(ValueError) as ctx:
            r.register_refusal(bad)
        self.assertIn("Conflicting refusal record", str(ctx.exception))

        # On a fresh registry, assess_request catches record_id != computed_record_id
        fresh_r = s.ScopedAdmissionRegistry()
        fresh_r.register_refusal(bad)
        elig, reason = fresh_r.assess_request(request)
        self.assertEqual(elig, s.ReevalEligibility.APPLICABILITY_UNKNOWN)
        self.assertIn("corrupted", reason.lower())

    # ------------------------------------------------------------------------
    # R3: Mutable Result Context Anti-Aliasing
    # ------------------------------------------------------------------------
    def test_r3_mutable_result_context_anti_aliasing(self):
        """R3: Post-retest context mutation fails closed and cannot admit unverified envelope."""
        r, cand_bytes, refusal, request = self._setup_registry()
        def success_fn(b, ctx):
            return s.RetestOutcome.SUCCESS, 150, b"trace"

        res = r.execute_retest(request, cand_bytes, success_fn)

        # Mutate result context dict directly
        res.context["budget_steps"] = 1

        # Must fail closed: hash integrity check or context divergence check catches tampering
        with self.assertRaises(ValueError):
            r.grant_scoped_admission(res)

        # Admission for budget 1 must NOT exist
        self.assertIsNone(r.admission_for(request.candidate_digest, {"budget_steps": 1}, "requirement_01", "evaluator_01"))

    # ------------------------------------------------------------------------
    # R4: Attempt Limits Durability Across Restarts
    # ------------------------------------------------------------------------
    def test_r4_attempts_durability_across_restarts(self):
        """R4: export_state and import_state preserve attempts_spent and admissions across restarts."""
        r, cand_bytes, refusal, request = self._setup_registry()
        def success_fn(b, ctx):
            return s.RetestOutcome.SUCCESS, 120, b"trace"

        # Burn all 3 attempts
        for i in range(3):
            req_i = dataclasses.replace(request, request_id=f"req_{i}", claimed_basis=f"basis_{i}")
            r.execute_retest(req_i, cand_bytes, success_fn)

        self.assertEqual(r.attempts_spent[refusal.record_id], 3)

        # Export state and restore into brand-new registry instance
        state = r.export_state()
        new_registry = s.ScopedAdmissionRegistry()
        new_registry.import_state(state)

        # Attempts must be preserved
        self.assertEqual(new_registry.attempts_spent[refusal.record_id], 3)

        # Further request must be BLOCKED_BY_EXISTING_EVIDENCE due to exhausted quota
        elig, reason = new_registry.assess_request(request)
        self.assertEqual(elig, s.ReevalEligibility.BLOCKED_BY_EXISTING_EVIDENCE)
        self.assertIn("quota exhausted", reason.lower())

    # ------------------------------------------------------------------------
    # R5: Candidate Binding Check Before Cache Lookup
    # ------------------------------------------------------------------------
    def test_r5_candidate_binding_checked_before_cache_lookup(self):
        """R5: Candidate bytes hash mismatch raises ValueError immediately, even if request was cached."""
        r, cand_bytes, refusal, request = self._setup_registry()
        def success_fn(b, ctx):
            return s.RetestOutcome.SUCCESS, 120, b"trace"

        # First execution succeeds and caches
        res1 = r.execute_retest(request, cand_bytes, success_fn)
        self.assertEqual(res1.outcome, s.RetestOutcome.SUCCESS)

        # Calling again with mismatched candidate bytes MUST raise ValueError, not return cached SUCCESS
        with self.assertRaises(ValueError) as ctx:
            r.execute_retest(request, b"completely different candidate bytes", success_fn)
        self.assertIn("Candidate tampering detected", str(ctx.exception))

    # ------------------------------------------------------------------------
    # R6: Nonexistent / Cyclic Antecedent Proof DAG Rejected
    # ------------------------------------------------------------------------
    def test_r6_nonexistent_and_cyclic_antecedent_proof_rejected(self):
        """R6: verify_unsat_certificate checks antecedent referential integrity, acyclicity, and axiom grounding."""
        # Nonexistent antecedent 999
        proof_nonexistent = {
            1: sm.ResolutionProofNode(1, [1], "input"),
            2: sm.ResolutionProofNode(2, [], "learned", antecedents=[999])
        }
        self.assertFalse(sm.verify_unsat_certificate(proof_nonexistent))

        # Missing empty clause
        proof_no_empty = {
            1: sm.ResolutionProofNode(1, [1], "input")
        }
        self.assertFalse(sm.verify_unsat_certificate(proof_no_empty))

        # Cyclic antecedents
        proof_cycle = {
            1: sm.ResolutionProofNode(1, [], "learned", antecedents=[2]),
            2: sm.ResolutionProofNode(2, [1], "learned", antecedents=[1])
        }
        self.assertFalse(sm.verify_unsat_certificate(proof_cycle))

        # Ungrounded derivation (no input or theory_lemma roots)
        proof_ungrounded = {
            1: sm.ResolutionProofNode(1, [], "learned", antecedents=[2]),
            2: sm.ResolutionProofNode(2, [1], "other", antecedents=[])
        }
        self.assertFalse(sm.verify_unsat_certificate(proof_ungrounded))

    # ------------------------------------------------------------------------
    # R7: Finite Domain Check Classified Correctly
    # ------------------------------------------------------------------------
    def test_r7_finite_domain_check_classified_as_finite_satisfied(self):
        """R7: Piecewise spec failing outside finite domain returns FINITE_DOMAIN_SATISFIED, not PROVED_CORRECT."""
        loop = c.CEGISLoop(verifier_domain=["a", "b"])
        # Spec agrees on 'a' and 'b', but diverts on 'z'
        spec = lambda x: "a" if x[0] == "z" else x[0]
        res = loop.synthesize(spec, input_arity=1, primitives=[I], max_ast_size=1)

        self.assertEqual(res.status, c.SynthesisStatus.FINITE_DOMAIN_SATISFIED)
        self.assertIsNone(res.proof_dag)
        self.assertEqual(res.program, I)
        # Evaluator correctly fails on z
        self.assertNotEqual(loop._evaluate_term(res.program, ("z",)), spec(("z",)))

    # ------------------------------------------------------------------------
    # R8: Dialectical Retest Without SMT Proof
    # ------------------------------------------------------------------------
    def test_r8_dialectical_retest_without_smt_proof_is_not_smt_verified(self):
        """R8: Empirical scoped admission sets smt_verified=False when proof_dag is absent."""
        r, cand_bytes, refusal, request = self._setup_registry()
        def success_fn(b, ctx):
            return s.RetestOutcome.SUCCESS, 120, b"trace"

        orchestrator = d.DialecticalOrchestrator(r)
        report = orchestrator.discover_and_promote(refusal.record_id, cand_bytes, success_fn)

        self.assertFalse(report.smt_verified)
        self.assertIsNone(report.proof_dag)
        self.assertIsNotNone(report.scoped_admission)

    # ------------------------------------------------------------------------
    # R9: Axiomatic Edge Claim Binding & Derivation Steps
    # ------------------------------------------------------------------------
    def test_r9_warrant_axiomatic_edge_binding_and_nonempty_steps(self):
        """R9: Axiomatic claim audit requires non-empty derivation steps and claim.tau == rule_name."""
        sk, pk = generate_keypair()
        verifier = w.WarrantVerifier(w.TrustConfig(trusted_author_pks={pk}))

        # Empty derivation steps must fail
        claim_empty_steps = w.EdgeClaim.create_and_sign(
            "parent", "K", "I", "succ", w.Polarity.AFFIRM,
            w.AxiomaticWitness([], "I x -> x", "Identity"),
            sk, pk
        )
        v1 = verifier.audit_claim(claim_empty_steps)
        self.assertEqual(v1.status, w.VerificationStatus.FAIL)
        self.assertIn("empty derivation steps", v1.reason)

        # Mismatched tau (tau="K" vs rule="I x -> x") must fail
        claim_mismatch_tau = w.EdgeClaim.create_and_sign(
            "parent", "K", "I", "succ", w.Polarity.AFFIRM,
            w.AxiomaticWitness(["step 1"], "I x -> x", "Identity"),
            sk, pk
        )
        v2 = verifier.audit_claim(claim_mismatch_tau)
        self.assertEqual(v2.status, w.VerificationStatus.FAIL)
        self.assertIn("does not match witness rule", v2.reason)

        # Valid axiomatic claim with bound tau and non-empty steps passes
        rule = "I x -> x"
        claim_valid = w.EdgeClaim.create_and_sign(
            "parent", rule, "I", "succ", w.Polarity.AFFIRM,
            w.AxiomaticWitness(["step 1: apply identity rewrite"], rule, w.ALGEBRAIC_SOUND_RULES[rule]),
            sk, pk
        )
        v3 = verifier.audit_claim(claim_valid)
        self.assertEqual(v3.status, w.VerificationStatus.PASS)

    # ------------------------------------------------------------------------
    # R10: SMT Unknown Never Promoted to Correct
    # ------------------------------------------------------------------------
    def test_r10_cegis_unknown_solver_not_promoted_to_proved_correct(self):
        """R10: SMT solver returning UNKNOWN yields INCONCLUSIVE, never PROVED_CORRECT."""
        class MockUnknownSolver:
            def solve_smt2(self, *a, **k):
                return sm.SMTResult(status=sm.SMTStatus.UNKNOWN)

        loop = c.CEGISLoop(verifier_domain=["a", "b"])
        loop.smt = MockUnknownSolver()
        res = loop.synthesize(lambda x: x[0], input_arity=1, primitives=[I], max_ast_size=1)

        self.assertNotEqual(res.status, c.SynthesisStatus.PROVED_CORRECT)
        self.assertEqual(res.status, c.SynthesisStatus.INCONCLUSIVE)
        self.assertIsNone(res.proof_dag)

    # ------------------------------------------------------------------------
    # R11: Host-Enforced Execution Deadline
    # ------------------------------------------------------------------------
    def test_r11_host_enforced_execution_deadline(self):
        """R11: execute_retest bounds long-running callbacks with timeout, burning fuel without hanging."""
        r, cand_bytes, refusal, request = self._setup_registry()
        def hanging_fn(b, ctx):
            time.sleep(10)
            return s.RetestOutcome.SUCCESS, 100, b"never reached"

        t_start = time.time()
        res = r.execute_retest(request, cand_bytes, hanging_fn, timeout_sec=0.2)
        elapsed = time.time() - t_start

        self.assertLess(elapsed, 1.0)
        self.assertEqual(res.outcome, s.RetestOutcome.INCONCLUSIVE)
        self.assertIn(b"TIMEOUT", res.evidence_bytes)
        self.assertEqual(r.attempts_spent[refusal.record_id], 1)
        self.assertIsNone(r.grant_scoped_admission(res))


if __name__ == "__main__":
    unittest.main()
